export type Lang='en'|'de';
export type Copy={en:string;de:string};
export type Building={id:string;name:Copy;short:Copy;use:string;area:number;height:string;dimensions:Copy;levels:string[];description:Copy;construction:Copy;features:Copy[];images:string[];page:number;point:[number,number];outline:string};
export const buildings:Building[]=[
{id:'communications',name:{en:'Communications Center',de:'Kommunikationszentrum'},short:{en:'Communications',de:'Kommunikation'},use:'Culture',area:20000,height:'> 60',dimensions:{en:'Ø approx. 49 m',de:'Ø ca. 49 m'},levels:['B2','B1','G','M1','M2','M3','1','2','3','4','5','6','7','8'],description:{en:'A place to experience artificial intelligence. Exhibitions, conferences and learning bring the public, researchers and practitioners together at the heart of the campus.',de:'Künstliche Intelligenz erleben. Ausstellungen, Konferenzen und Bildung bringen Öffentlichkeit, Forschung und Praxis im Herzen des Campus zusammen.'},construction:{en:'A cylindrical reinforced-concrete structure with a reflective facade. Eight upper floors, three mezzanines and two basement levels are linked by lifts, stairs and escalators.',de:'Zylindrischer Stahlbetonbau mit spiegelnder Fassade. Acht Obergeschosse, drei Zwischengeschosse und zwei Untergeschosse werden durch Aufzüge, Treppen und Rolltreppen verbunden.'},features:[{en:'Exhibitions & AI education',de:'Ausstellungen & KI-Bildung'},{en:'Conference and seminar spaces',de:'Konferenz- und Seminarräume'},{en:'Penthouse bar',de:'Bar im Dachgeschoss'}],images:['kommunikationszentrum_tag_landscape','kommunikationszentrum_nacht_landscape','kommunikationszentrum_tag','kommunikationszentrum_nacht','piazza'],page:1,point:[881,650],outline:'847,613 858,600 884,594 908,600 920,614 925,703 908,718 876,721 848,707'},
{id:'mobility',name:{en:'Mobility Hub',de:'Mobility Hub'},short:{en:'Mobility Hub',de:'Mobility Hub'},use:'Mobility',area:66000,height:'28',dimensions:{en:'Approx. 71 × 119 m',de:'Ca. 71 × 119 m'},levels:['B2','B1','G','1','2','3','4','5'],description:{en:'The gateway to the campus. Arrive, switch to micromobility, and move into a connected campus. Underground logistics distribute supplies across the site.',de:'Das Tor zum Campus. Ankommen, auf Mikromobilität umsteigen und den vernetzten Campus entdecken. Die unterirdische Logistik versorgt das gesamte Areal.'},construction:{en:'Six storeys and two basement levels in reinforced concrete, with a facade of vertical ceramic elements in varied colours.',de:'Sechs Geschosse und zwei Untergeschosse in Stahlbetonbauweise. Vertikale Keramikelemente in unterschiedlichen Farbtönen prägen die Fassade.'},features:[{en:'Parking & micromobility',de:'Parken & Mikromobilität'},{en:'Underground logistics connection',de:'Unterirdische Logistikanbindung'},{en:'Atrium & fitness area',de:'Atrium & Fitnessbereich'}],images:['mobility_hub','luftbild'],page:2,point:[480,706],outline:'410,682 432,655 517,651 555,662 542,744 470,772 416,743'},
{id:'restaurant',name:{en:'Restaurant',de:'Restaurant'},short:{en:'Restaurant',de:'Restaurant'},use:'Hospitality',area:17000,height:'33',dimensions:{en:'Approx. 50 × 50 m',de:'Ca. 50 × 50 m'},levels:['B2','B1','G','1','2','3','4'],description:{en:'From an everyday lunch to a special dinner. A ground-floor lounge and a fine-dining restaurant with campus views make food a shared experience.',de:'Von der täglichen Mittagspause bis zum besonderen Abendessen. Lounge im Erdgeschoss und Fine Dining mit Campusblick machen Gastronomie zum gemeinsamen Erlebnis.'},construction:{en:'Reinforced-concrete flat slabs create flexible spaces. Large glazed grotto facades bring light and depth into the building. A plant room is provided at the fifth upper floor.',de:'Stahlbeton-Flachdecken ermöglichen flexible Räume. Großflächige gläserne Grottofassaden bringen Licht und Tiefe in das Gebäude. Eine Technikzentrale liegt im fünften Obergeschoss.'},features:[{en:'More than 1,000 seats',de:'Mehr als 1.000 Sitzplätze'},{en:'Lounge & fine dining',de:'Lounge & Fine Dining'},{en:'Temperature-controlled logistics',de:'Temperierte Logistik'}],images:['restaurant_ost','restaurant_sud','piazza'],page:3,point:[711,675],outline:'668,646 730,634 757,646 756,714 680,720 668,703'},
{id:'living-lab',name:{en:'Living Lab',de:'Reallabor'},short:{en:'Living Lab',de:'Reallabor'},use:'Research',area:9900,height:'20',dimensions:{en:'Approx. 50 × 87 m',de:'Ca. 50 × 87 m'},levels:['B2','B1','G','1'],description:{en:'A real-world testing ground for AI. Robotics, production equipment and digital solutions can be developed, tested and validated in purpose-built laboratory environments.',de:'Ein reales Testfeld für KI. Robotik, Produktionsanlagen und digitale Lösungen werden in speziell konzipierten Laborumgebungen entwickelt, erprobt und validiert.'},construction:{en:'Two full floors and two basement levels in timber-hybrid construction. Timber trusses and an integrated crane runway support technical applications in the hall.',de:'Zwei Vollgeschosse und zwei Untergeschosse in Holz-Hybridbauweise. Holzfachwerkträger und eine integrierte Kranbahn ermöglichen technische Anwendungen in der Halle.'},features:[{en:'Robotics hall / events up to 500 people',de:'Robotikhalle / Events bis 500 Personen'},{en:'Test data centre & workshops',de:'Test-Rechenzentrum & Werkstätten'},{en:'Seminars & campus bike garage',de:'Seminare & Campus-Fahrradgarage'}],images:['reallabor','reallabor_nord','promenaden_1'],page:4,point:[766,741],outline:'661,720 846,717 854,739 841,767 660,768'},
{id:'high-rise',name:{en:'High-rise Building',de:'Hochhaus'},short:{en:'High-rise',de:'Hochhaus'},use:'Work',area:19300,height:'44',dimensions:{en:'Approx. 30 × 50 m',de:'Ca. 30 × 50 m'},levels:['B2','B1','G','1','2','3','4','5','6','7','8','9'],description:{en:'Flexible workspace for the people building AI. Adaptable rental units, meeting rooms and shared living rooms support focused work and spontaneous encounters.',de:'Flexible Arbeitswelten für Menschen, die KI entwickeln. Anpassbare Mieteinheiten, Besprechungsräume und gemeinsame Wohnzimmer fördern konzentriertes Arbeiten und spontane Begegnungen.'},construction:{en:'Ten storeys and two basement levels in timber-hybrid construction. A stepped curtain facade, integrated photovoltaic modules and a rooftop PV pergola produce renewable energy.',de:'Zehn Geschosse und zwei Untergeschosse in Holz-Hybridbauweise. Gefaltete Vorhangfassade, integrierte PV-Module und eine PV-Pergola auf dem Dach erzeugen erneuerbare Energie.'},features:[{en:'Flexible offices for members & partners',de:'Flexible Büros für Mitglieder & Partner'},{en:'Double-height shared living rooms',de:'Zweigeschossige gemeinsame Wohnzimmer'},{en:'Photovoltaic facade & roof',de:'Photovoltaik an Fassade & Dach'}],images:['hochhaus','hochhaus_eingang','hochhaus_ost','hochhaus_sud','promenaden_1','promenaden_2'],page:5,point:[587,716],outline:'563,660 622,657 632,674 621,761 557,762 555,694'},
{id:'startup',name:{en:'Startup & Innovation Center',de:'Start-Up & Innovation Center'},short:{en:'Startup Center',de:'Start-Up Center'},use:'Work',area:6500,height:'13',dimensions:{en:'Approx. 50 × 50 m',de:'Ca. 50 × 50 m'},levels:['B2','B1','G','1'],description:{en:'Room for ideas, with space to grow. Early-stage companies and project teams work, meet and connect around a green central gathering place.',de:'Raum für Ideen, mit Potenzial für Wachstum. Junge Unternehmen und Projektteams arbeiten und vernetzen sich rund um einen grünen zentralen Treffpunkt.'},construction:{en:'Three equally sized structures with timber portal frames, pitched roofs and coloured timber cladding. Two full floors and two basement levels provide work and gathering spaces.',de:'Drei gleich große Baukörper mit Holzportalträgern, Satteldächern und farbiger Holzverkleidung. Zwei Vollgeschosse und zwei Untergeschosse bieten Arbeits- und Begegnungsräume.'},features:[{en:'Offices & meeting rooms',de:'Büros & Besprechungsräume'},{en:'Central green gathering space',de:'Zentraler grüner Treffpunkt'},{en:'Tiered seating & event kitchen',de:'Tribüne & Eventküche'}],images:['start_up_center','promenaden_2','promenaden_1'],page:6,point:[643,693],outline:'628,680 645,668 657,680 655,709 630,717'}
];
export const uses:Record<string,Copy>={All:{en:'All uses',de:'Alle Nutzungen'},Culture:{en:'Culture & learning',de:'Kultur & Bildung'},Mobility:{en:'Mobility',de:'Mobilität'},Hospitality:{en:'Hospitality',de:'Gastronomie'},Research:{en:'Research & testing',de:'Forschung & Erprobung'},Work:{en:'Work & innovation',de:'Arbeit & Innovation'}};
export const amenities=[
{id:'piazza',title:{en:'The campus piazza',de:'Die Campus-Piazza'},text:{en:'The shared heart of the campus. A place to meet, pause and exchange ideas.',de:'Das gemeinsame Herz des Campus. Ein Ort zum Treffen, Verweilen und Austauschen.'},image:'piazza',kind:'Community'},
{id:'promenade',title:{en:'Connected promenades',de:'Vernetzte Promenaden'},text:{en:'Walkable connections between work, research and public life.',de:'Fußläufige Verbindungen zwischen Arbeit, Forschung und öffentlichem Leben.'},image:'aussenanlagen_promenade',kind:'Outdoors'},
{id:'park',title:{en:'Room to breathe',de:'Raum zum Durchatmen'},text:{en:'Landscape and outdoor spaces bring a different rhythm to the working day.',de:'Landschaft und Freiräume bringen einen anderen Rhythmus in den Arbeitstag.'},image:'aussenanlage',kind:'Outdoors'},
{id:'dining',title:{en:'Food & conversation',de:'Essen & Begegnung'},text:{en:'A restaurant with more than 1,000 seats, a lounge and fine dining.',de:'Restaurant mit mehr als 1.000 Sitzplätzen, Lounge und Fine Dining.'},image:'restaurant_sud',kind:'Food'},
{id:'learning',title:{en:'Discover artificial intelligence',de:'Künstliche Intelligenz entdecken'},text:{en:'Exhibitions, seminars and events open the campus to everyone.',de:'Ausstellungen, Seminare und Veranstaltungen öffnen den Campus für alle.'},image:'kommunikationszentrum_tag_landscape',kind:'Community'},
{id:'movement',title:{en:'Arrive. Switch. Explore.',de:'Ankommen. Umsteigen. Entdecken.'},text:{en:'The Mobility Hub connects arrivals, micromobility and a fitness area.',de:'Der Mobility Hub verbindet Ankunft, Mikromobilität und Fitnessbereich.'},image:'mobility_hub',kind:'Mobility'}
];
export const img=(name:string,thumb=false)=>`./media/${name}${thumb?'-thumb':''}.webp`;
