'use client';
import {useState} from 'react';
import {Expand,Scale,Check,X,Info} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Lang} from './data';
export type OfficeChoice={building:string;floor:string;suite:number};
const configs={
 'high-rise':{name:{en:'Office high-rise',de:'Bürohochhaus'},image:'./media/office-concept.webp',levels:['1','2','3','4','5','6','7','8','9'],areas:[180,240,150,210],desks:[16,24,12,20],rooms:[1,2,1,2],types:{en:['Team suite','Partner suite','Focus suite','Project suite'],de:['Team-Büro','Partner-Büro','Fokus-Büro','Projekt-Büro']}},
 startup:{name:{en:'Start-up Center',de:'Start-Up Center'},image:'./media/startup-concept.webp',levels:['G','1'],areas:[80,120,65,100],desks:[8,12,6,10],rooms:[1,1,0,1],types:{en:['Launch studio','Growth studio','Sprint studio','Venture studio'],de:['Launch-Studio','Growth-Studio','Sprint-Studio','Venture-Studio']}}
};
type PlanBuilding=keyof typeof configs;
const bounds:Record<PlanBuilding,number[][]>={
 'high-rise':[[7.5,11.8,36.2,31.2],[56.2,11.8,36.2,31.2],[7.5,55.2,36.2,33.1],[56.2,55.2,36.2,33.1]],
 startup:[[11,13.3,32.7,28.2],[56.2,13.3,32.5,28.2],[11,56.9,32.7,27.5],[56.2,56.9,32.5,27.5]]
};
const key=(c:OfficeChoice)=>`${c.building}:${c.floor}:${c.suite}`;
function Plan({building,floor,selected,onSelect,choices,lang}:{building:PlanBuilding;floor:string;selected:number|null;onSelect:(s:number)=>void;choices:OfficeChoice[];lang:Lang}){
 const config=configs[building];return <svg className="office-plan" viewBox="0 0 100 100" role="group" aria-label={lang==='en'?'Illustrative floor plan. Select an office.':'Beispielgrundriss. Büro auswählen.'}>
 <image href={config.image} width="100" height="100"/>
 {bounds[building].map(([x,y,w,h],i)=>{const chosen=choices.some(c=>key(c)===key({building,floor,suite:i}));return <g key={i} tabIndex={0} role="button" aria-pressed={selected===i} aria-label={`${config.types[lang][i]}, ${config.areas[i]} m², ${config.desks[i]} ${lang==='en'?'example desks':'Beispielarbeitsplätze'}`} onClick={()=>onSelect(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(i)}}} className={(selected===i?'selected ':'')+(chosen?'shortlisted':'')}><rect className="office-hit" x={x} y={y} width={w} height={h}/><rect className="office-tag" x={x+w/2-8} y={y+h/2-3.5} width="16" height="7" rx="1"/><text x={x+w/2} y={y+h/2} textAnchor="middle" dominantBaseline="central">{floor}-{String(i+1).padStart(2,'0')}{chosen?' ✓':''}</text></g>})}</svg>
}
export default function OfficePlans({building,lang,choices,onChoices,onOpenChange}:{building:string;lang:Lang;choices:OfficeChoice[];onChoices:(c:OfficeChoice[])=>void;onOpenChange:(open:boolean)=>void}){
 const [open,setOpen]=useState(false),[view,setView]=useState<'plan'|'compare'>('plan'),[active,setActive]=useState<PlanBuilding>(building==='startup'?'startup':'high-rise'),[floor,setFloor]=useState(building==='startup'?'G':'1'),[suite,setSuite]=useState<number|null>(null),[notice,setNotice]=useState('');
 const t=(en:string,de:string)=>lang==='en'?en:de,config=configs[active];
 function changeOpen(value:boolean){setOpen(value);onOpenChange(value)}
 function switchBuilding(value:PlanBuilding){setActive(value);setFloor(configs[value].levels[0]);setSuite(null);setNotice('');setView('plan')}
 function toggle(){if(suite===null)return;const entry={building:active,floor,suite};if(choices.some(c=>key(c)===key(entry))){onChoices(choices.filter(c=>key(c)!==key(entry)));setNotice('')}else if(choices.length<3){onChoices([...choices,entry]);setNotice('')}else setNotice(t('Remove one office to compare another. Maximum three.','Entfernen Sie ein Büro, um ein anderes zu vergleichen. Maximal drei.'))}
 const picked=suite!==null&&choices.some(c=>key(c)===key({building:active,floor,suite}));
 const levels=<div className="office-levels"><label>{t('Example floor','Beispielebene')}<select value={floor} onChange={e=>{setFloor(e.target.value);setSuite(null)}}>{config.levels.map(f=><option key={f} value={f}>{f==='G'?t('Ground floor','Erdgeschoss'):t('Floor ','Etage ')+f}</option>)}</select></label><span>{t('Typical layout reused across levels','Typisches Layout auf allen Ebenen')}</span></div>;
 const profile=suite===null?<p className="office-instruction">{t('Click an office in the plan to see its example details.','Wählen Sie ein Büro im Grundriss für Beispieldaten.')}</p>:<div className="office-profile"><span className="eyebrow">{config.name[lang]} · {floor}-{String(suite+1).padStart(2,'0')}</span><h3>{config.types[lang][suite]}</h3><div className="office-stats"><strong>{config.areas[suite]} <small>m²</small></strong><span>{config.desks[suite]} {t('desks','Arbeitsplätze')}</span><span>{config.rooms[suite]} {t('meeting rooms','Besprechungsräume')}</span></div><p>{t('Example area, capacity and layout—not confirmed availability.','Beispielfläche, Kapazität und Layout – keine bestätigte Verfügbarkeit.')}</p><button className={picked?'outline-btn':'primary-btn'} onClick={toggle}>{picked?<Check size={16}/>:<Scale size={16}/>} {picked?t('Remove from comparison','Aus Vergleich entfernen'):t('Add to comparison','Zum Vergleich hinzufügen')}</button>{notice&&<p role="status">{notice}</p>}</div>;
 return <div className="office-explorer"><div className="illustrative"><Info size={15}/>{t('AI concept plan · illustrative only','KI-Konzeptgrundriss · nur beispielhaft')}</div>{levels}<Plan building={active} floor={floor} selected={suite} onSelect={setSuite} choices={choices} lang={lang}/>{profile}<div className="office-actions"><button className="outline-btn" onClick={()=>{setView('plan');changeOpen(true)}}><Expand size={16}/>{t('Open floor explorer','Grundriss öffnen')}</button><button className="outline-btn" onClick={()=>{setView('compare');changeOpen(true)}}><Scale size={16}/>{t('Compare offices','Büros vergleichen')} ({choices.length})</button></div>
 <Dialog open={open} onOpenChange={changeOpen}><DialogContent className="campus-dialog office-dialog"><DialogTitle>{t('Explore & compare offices','Büros entdecken & vergleichen')}</DialogTitle><DialogDescription>{t('AI-generated concept plans and assumed office data. Not official IPAI designs.','KI-generierte Konzeptgrundrisse und angenommene Bürodaten. Keine offiziellen IPAI-Entwürfe.')}</DialogDescription><div className="office-dialog-nav"><div>{(Object.keys(configs) as PlanBuilding[]).map(id=><button className={view==='plan'&&active===id?'active':''} key={id} onClick={()=>switchBuilding(id)}>{configs[id].name[lang]}</button>)}</div><button className={view==='compare'?'active':''} onClick={()=>setView('compare')}><Scale size={16}/>{t('Comparison','Vergleich')} ({choices.length}/3)</button></div>
 {view==='plan'?<div className="office-large-layout"><Plan building={active} floor={floor} selected={suite} onSelect={setSuite} choices={choices} lang={lang}/><div>{levels}{profile}<p className="source-note">{t('Four example suites share circulation and services. Select up to three offices across buildings or floors.','Vier Beispieleinheiten teilen Erschließung und Servicebereiche. Wählen Sie bis zu drei Büros aus verschiedenen Gebäuden oder Etagen.')}</p></div></div>:choices.length?<div className="office-comparison"><div className="office-comparison-scroll"><table><caption>{t('Illustrative office comparison','Beispielhafter Bürovergleich')}</caption><thead><tr><th>{t('Office','Büro')}</th>{choices.map(c=>{const b=configs[c.building as PlanBuilding];return <th key={key(c)}><button className="office-remove" aria-label={t('Remove office','Büro entfernen')} onClick={()=>onChoices(choices.filter(x=>key(x)!==key(c)))}><X size={15}/></button><span>{b.name[lang]}</span><strong>{c.floor}-{String(c.suite+1).padStart(2,'0')}</strong><small>{b.types[lang][c.suite]}</small></th>})}</tr></thead><tbody><tr><th>{t('Location in plan','Lage im Grundriss')}</th>{choices.map(c=><td key={key(c)}><Plan building={c.building as PlanBuilding} floor={c.floor} selected={c.suite} onSelect={()=>{setActive(c.building as PlanBuilding);setFloor(c.floor);setSuite(c.suite);setView('plan')}} choices={[]} lang={lang}/></td>)}</tr>{[
 [t('Example area','Beispielfläche'),(c:OfficeChoice)=>`${configs[c.building as PlanBuilding].areas[c.suite]} m²`],
 [t('Example desks','Beispielarbeitsplätze'),(c:OfficeChoice)=>configs[c.building as PlanBuilding].desks[c.suite]],
 [t('Meeting rooms','Besprechungsräume'),(c:OfficeChoice)=>configs[c.building as PlanBuilding].rooms[c.suite]],
 [t('Area per desk','Fläche je Arbeitsplatz'),(c:OfficeChoice)=>`${(configs[c.building as PlanBuilding].areas[c.suite]/configs[c.building as PlanBuilding].desks[c.suite]).toFixed(1)} m²`],
 [t('Floor','Etage'),(c:OfficeChoice)=>c.floor==='G'?t('Ground floor','Erdgeschoss'):c.floor]
 ].map(([title,value])=><tr key={String(title)}><th>{String(title)}</th>{choices.map(c=><td key={key(c)}>{(value as (c:OfficeChoice)=>string|number)(c)}</td>)}</tr>)}</tbody></table></div><p className="source-note">{t('All office figures are assumptions for this prototype. No prices or availability are implied.','Alle Büroangaben sind Annahmen für diesen Prototyp. Keine Preis- oder Verfügbarkeitsangaben.')}</p><button className="outline-btn" onClick={()=>setView('plan')}>{t('Select more offices','Weitere Büros auswählen')}</button></div>:<div className="empty"><Scale/><h3>{t('Build your office shortlist','Ihre Büroauswahl zusammenstellen')}</h3><p>{t('Select an office in either plan, then add it to comparison.','Wählen Sie ein Büro in einem Grundriss und fügen Sie es zum Vergleich hinzu.')}</p><button className="primary-btn" onClick={()=>setView('plan')}>{t('Explore floor plans','Grundrisse entdecken')}</button></div>}
 </DialogContent></Dialog></div>
}
